Auth (#8)
* WORK IN PROGRESS

Get, Post, Put, Delete operations for the users and devices classes.

ERROR: ModuleNotFoundError: No module named 'devices'

* HALF COMMIT

Added API for POST GET PUT DELETE
for the Users and Devices classes

Error: ModuleNotFoundError: No module named 'devices'

* Fixed ModuleNotFoundError

* added .env file

* Created API Endpoints and Generated Documentation For Donor, Warehouse and JWSToken Models

* updated unit tests of all restapi endpoints in the respective app/test.py files, renamed auth to authen to avoid clashing with django.contrib.auth,

* style: format code with Black and isort

This commit fixes the style issues introduced in a812c10 according to the output
from Black and isort.

Details: https://github.com/Angaza-Inventory-System/inventory-backend/pull/7

* added documentation to all of the restAPI test.py files detailing info about testcase and routes

* Added filtering and pagination for for Devices, Warehouses and Donors

* style: format code with Black and isort

This commit fixes the style issues introduced in c56f01d according to the output
from Black and isort.

Details: https://github.com/Angaza-Inventory-System/inventory-backend/pull/7

* things for testing

* style: format code with Black and isort

This commit fixes the style issues introduced in 4b17a89 according to the output
from Black and isort.

Details: https://github.com/Angaza-Inventory-System/inventory-backend/pull/7

* Added missing requirements

* Created .env.example

* chore: Added API endpoints to README

* Darryl Commit

* QOL changes, fixed documentation, deleted authen links

* Merge branch 'API_Endpoints' of https://github.com/Angaza-Inventory-System/inventory-backend into API_Endpoints

* style: format code with Black and isort

This commit fixes the style issues introduced in 83eb282 according to the output
from Black and isort.

Details: https://github.com/Angaza-Inventory-System/inventory-backend/pull/7

* Implemented JWT authentication for API endpoints

Created Better Login Endpoint

* Half Commit - Broken Auth

* chore: Update requirements.txt with djangorestframework-simplejwt

* Applied formatter

* Fixed auth problem by using BaseUser classes from Django

* added djangorestframework-simplejwt

* Fixed Token Blacklisting

* Edited docs and removed some redundant code

* style: format code with Black and isort

This commit fixes the style issues introduced in 23d1017 according to the output
from Black and isort.

Details: https://github.com/Angaza-Inventory-System/inventory-backend/pull/8

* Merge branch 'main' into auth